version: "2"
run:
  timeout: 60s

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: quanta

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - revive
    